'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30128.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property ammus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ammus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ammus_oik_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ammus_oik_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Box1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Box1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pistol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pistol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_ase_alas_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_ase_alas_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_ase_oik_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_ase_oik_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_ase_vas_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_ase_vas_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_ase_ylös() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_ase_ylös", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_puukko_oik_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_puukko_oik_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_puukko_oik_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_puukko_oik_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_puukko_vas_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_puukko_vas_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ukko_puukko_vas_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ukko_puukko_vas_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombi_elossa_oik_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombi_elossa_oik_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombi_elossa_vas_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombi_elossa_vas_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombi_oik_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombi_oik_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property zombi_vas_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("zombi_vas_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
